### ISSUE TITLE
Should we proxy or core functions?

### ISSUE THREAD

**Issue by radmen** [nkkollaw/zubr#27]
Or just a *subset* which requires fixing?

**Comment by nkkollaw** [comment]
Sorry, can you elaborate? You mean if we should include all functions, or only those who don't match our guidelines?

If that is the case, I'd say all of them, so that you can just use \NAMESPACE\function_name instead of function_name as a habit.

We should limit ourselves to core functions and extensions that come with the language, though.

**Comment by radmen** [comment]
You've posted answer for this in https://github.com/nkkollaw/php/issues/20#issuecomment-319705197 ;)

> We should limit ourselves to core functions and extensions that come with the language, though.

Agreed. For extensions we can create a separate packages.

Guess I can close this issue. Thanks!
